FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /app
COPY ./Cluster.RealTime/*.csproj ./Cluster.RealTime/
COPY ./Cluster.Messages/*.csproj ./Cluster.Messages/
COPY ./Cluster.Persistence/*.csproj ./Cluster.Persistence/
WORKDIR /app/Cluster.RealTime/
RUN dotnet restore

RUN mkdir /usr/share/dotnet/sdk/NuGetFallbackFolder
WORKDIR /app
COPY ./Cluster.RealTime/ ./Cluster.RealTime/
COPY ./Cluster.Messages/ ./Cluster.Messages/
COPY ./Cluster.Persistence/ ./Cluster.Persistence/
WORKDIR /app/Cluster.RealTime/
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-alpine3.11 AS base
EXPOSE 80
WORKDIR /app
COPY --from=build /app/Cluster.RealTime/out .
ENTRYPOINT ["dotnet", "Cluster.RealTime.dll"]