FROM node:14.17-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ /app/
ARG API_URL
ENV API_URL=$API_URL
RUN npm run build

FROM nginx:1.17.1-alpine
COPY --from=build /app/dist/Cluster-Web /usr/share/nginx/html/
EXPOSE 80